export const listStyles = (theme) => ({
  pageContainer: {
    backgroundColor: theme.palette.bgGray,
    margin: "0 calc(24px + 2vw)",
    marginTop: "60px",
    height: "calc(100% - 60px)",
    width: "100%",
  },
  searchMenu: {
    minWidth: "fit-content",
    cursor: "pointer !important",
    display: "flex",
  },
  cancelSearch: {
    color: "#a3a5a9",
    "&:hover": {
      color: "#536586",
    },
  },
  docStats: {
    border: "solid 1px gray",
    padding: "0 1vw",
    borderRadius: "6px",
    color: "gray",
  },
  helperTooltip: {
    zIndex: "99999 !important",
    opacity: "1 !important",
    backgroundColor: "#157fff !important",
    boxShadow: "0px 1px 6px rgba(99, 128, 157, 0.4) !important",
    padding: "1vh 1vw !important",
    color: "white !important",
    fontWeight: "500 !important",
  },
  vRadio: {
    marginRight: "1vw",
  },
  selectOpen: {
    borderRight: "1px solid #8A8886",
    borderLeft: "none !important",
  },
  exportDocs: {
    fontSize: "12px",
    cursor: "pointer",
    color: theme.palette.black1,
    display: "flex",
    flexDirection: "row",
  },
  radioRoot: {
    paddingTop: "0 !important",
    paddingBottom: "0 !important",
    paddingLeft: "0 !important",
    paddingRight: "4px",
    "&:last-child": {
      paddingLeft: "1vw  !important",
    },
  },
  radioCont: {
    display: "flex",
    flexDirection: "row !important",
  },
  smallRadioButton: {
    "& svg": {
      width: "0.7em",
      height: "0.7em",
    },
  },
  docFilterIcon: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    marginRight: "0.5vw",
  },
  menuPaper: {
    // maxHeight: '30%'
    maxHeight: "250px",
  },
  rowLink: {
    cursor: "pointer",
    // textDecoration: 'underline',
    fontWeight: "600",
    width: "12vw",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    cursor: "pointer",
    color: "#314059",
  },
  rowLinkDis: {
    cursor: "pointer",
    fontWeight: "500",
    width: "12vw",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    cursor: "pointer",
    color: theme.palette.headerGray,
  },
  classMenu: {
    fontSize: "11px !important",
    [theme.breakpoints.up("md")]: {
      fontSize: "12px !important",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "14.5px !important",
    },
  },
  pagination: {
    marginTop: "3vh",
    display: "flex",
    justifyContent: "flex-end",
    marginRight: "calc(24px + 1vw)",
  },
  tableCellRoot: {
    padding: "1vh 1vw !important",
  },
  disRowLink: {
    cursor: "pointer",
    textDecoration: "underline",
    fontWeight: "500",
    width: "8vw",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    cursor: "not-allowed",
    color: "gray",
  },
  percentageLine: {
    height: "3px",
    border: "none",
    margin: "0",
    borderRadius: "6px",
  },
  adConfigSection: {
    flex: "1",
    margin: "2vw 1vw",
    border: "solid 1px rgba(0, 0, 0, 0.05)",
    borderRadius: "10px",
    padding: "2vw",
  },
  percentageBar: {
    border: `none`,
    backgroundColor: "#f2f2f2",
    width: "100%",
    borderRadius: "6px",
    height: "3px",
  },
  cfScore: {
    color: theme.palette.headerGray,
    marginLeft: "8px",
  },
  newConfigButton: {
    cursor: "pointer",
    color: theme.palette.blue,
    textDecoration: "underline",
    fontSize: "13px",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    fontWeight: "500",
  },
  miniHeader: {
    color: theme.palette.black1,
    padding: "2.5vh 2vw",
    display: "flex",
    justifyContent: "space-between",
    "@media screen and  (max-width: 1280px) and (min-height: 577px) and (max-height: 577px)":
      {
        padding: "1.5vh 2vw",
      },
  },
  docListHeader: {
    margin: "0 calc(24px + 1vw) 0 calc(24px + 1vw) !important",
    padding: "0 !important",
  },
  mappingListCont: {
    paddingTop: "33px",
    height: "calc(100% - 33px)",
  },
  selectAllDocs: {
    fontSize: "12px",
    cursor: "pointer",
    textDecoration: "underline",
    color: theme.palette.black1,
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
  },
  batchFilter: {
    backgroundColor: theme.palette.white,
    height: "fit-content",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    padding: "1px 0",
    marginRight: "4px",
    color: theme.palette.white,
    border: "1px solid #8A8886",
    borderRadius: "6px",
  },
  classFilter: {
    backgroundColor: theme.palette.white,
    height: "fit-content",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    padding: "0 1vh",
    marginRight: "1vw",
    boxShadow: "0px 1px 4px 0 rgba(92, 101, 132, 0.18)",
    border: "solid 2px black",
    borderRadius: "20px",
    color: theme.palette.black1,
  },
  batchFilterSelect: {
    paddingRight: "50px !important",
    backgroundColor: "transparent",
    color: "rgba(51, 54, 61, 0.8)",
    fontSize: "11px",
    paddingLeft: "1vw",
    fontWeight: "normal",
    fontSize: "11px !important",
    "@media (min-width: 1280px) and (max-height: 650px)": {
      fontSize: "10px !important",
    },
    "@media (min-width: 1680px)": {
      fontSize: "12.5px !important",
    },
    "@media (min-width: 1920px)": {
      fontSize: "14.5px !important",
    },
  },
  classFilterSelect: {
    backgroundColor: "transparent",
    color: theme.palette.black1,
    fontSize: "11px",
    paddingLeft: "4px",
    fontWeight: "normal",
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
    [theme.breakpoints.up("md")]: {
      fontSize: "12px",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "14.5px",
      paddingLeft: "1vw !important",
    },
  },
  batchFilterIcon: {
    color: "rgba(51, 54, 61, 0.8)",
    right: "0 !important",
    borderLeft: "1px solid #8A8886",
    marginTop: "-4px",
    height: "110%",
  },
  classFilterIcon: {
    color: `${theme.palette.black1} !important `,
    right: "0 !important",
  },
  configChip: {
    fontSize: "11px",
    color: theme.palette.blue,
    border: `solid 1px ${theme.palette.blue}`,
    padding: "0 !important",
    height: "fit-content",
  },
  configChipContainer: {
    fontSize: "11px",
    color: theme.palette.headerGray,
    marginLeft: "1vw",
  },
  selectedAllDocs: {
    fontSize: "11px",
    cursor: "pointer",
    borderRadius: "15px",
    padding: "0 1vw",
    color: theme.palette.black1,
    backgroundColor: "#e5e5e5",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
  },
  sortIcon: {
    marginTop: "-4px",
  },
  actionIcons: {
    color: theme.palette.blue,
  },
  tableLoader: {
    padding: "14vh 0",
  },
  identifiedBtn: {
    border: "solid 1px #339A42 !important",
    backgroundColor: "#339A42",
    color: `${theme.palette.white} !important`,
    "& $idNumber": {
      backgroundColor: theme.palette.white,
      color: "#2d9b3d",
    },
  },
  allFilesBtn: {
    border: "solid 1px #2F6EE9 !important",
    backgroundColor: `#2F6EE9 !important`,
    color: `${theme.palette.white} !important`,
    "& $allNumber": {
      backgroundColor: theme.palette.white,
      color: "black",
    },
  },

  unidentifiedBtn: {
    // border: 'solid 1px #F14336 !important',
    border: "solid 1px #157fff !important",
    backgroundColor: "#157fff",
    color: `${theme.palette.white} !important`,
    /* '& $unIdNumber': {
       backgroundColor: theme.palette.white,
       color: '#e83c3d',
     }*/
  },
  feedbackBtn: {
    border: "solid 1px #ecaf2b",
    backgroundColor: "#ecaf2b",
    color: theme.palette.white,
  },
  disabledIdBtn: {
    color: theme.palette.black1,
    border: "solid 1px #2d9b3d",
    backgroundColor: theme.palette.white,
    "&:hover": {
      /*backgroundColor: "#2d9b3d",
      color: theme.palette.white,
      '& $idNumber': {
        backgroundColor: theme.palette.white,
        color: '#2d9b3d',
      }*/
    },
  },
  disabledFdBtn: {
    color: theme.palette.black1,
    border: "solid 1px #ecaf2b",
    backgroundColor: theme.palette.white,
    "&:hover": {
      /*   backgroundColor: "#ecaf2b !important",
         color: theme.palette.white*/
    },
  },
  disabledUnIdBtn: {
    color: theme.palette.black1,
    border: "solid 1px #e83c3d",
    backgroundColor: theme.palette.white,
    "&:hover": {
      /*backgroundColor: "#e83c3d",
      color: theme.palette.white,
      // border: 'solid 1px #157fff',
      '& $unIdNumber': {
        backgroundColor: theme.palette.white,
        color: '#e83c3d',
      }*/
    },
  },
  disabledUnIdBtn1: {
    color: theme.palette.headerGray,
    // border: 'solid 1px #e83c3d',
    backgroundColor: theme.palette.white,
    border: "solid 1px #e83c3d",
  },
  idNumber: {
    color: theme.palette.white,
    backgroundColor: "#2d9b3d",
    minWidth: "30px",
    borderRadius: "3px",
    marginLeft: "1vw",
  },
  unIdNumber: {
    color: theme.palette.white,
    backgroundColor: "#e83c3d",
    minWidth: "30px",
    borderRadius: "3px",
    marginLeft: "1vw",
  },
  allNumber: {
    color: theme.palette.white,
    backgroundColor: "black",
    minWidth: "30px",
    borderRadius: "3px",
    marginLeft: "1vw",
  },
  idButtons: {
    padding: "0 1vw",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    cursor: "pointer",
    margin: "0 8px",
    borderRadius: "20px",
    fontWeight: "500",
    textAlign: "center",
    border: "1px solid #CDD5DC",
    color: "rgba(51, 52, 61,0.8)",
    "&:nth-child(1)": {
      "&:hover": {
        border: "solid 1px #339A42",
        color: "white",
        backgroundColor: "#339A42",
      },
    },
    "&:nth-child(2)": {
      "&:hover": {
        border: "solid 1px #157fff",
        color: "white",
        backgroundColor: "#157fff",
      },
    },
  },
  aidButton: {
    padding: "0 1vw",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    cursor: "pointer",
    margin: "0 8px",
    borderRadius: "20px",
    fontWeight: "500",
    textAlign: "center",
    border: "1px solid #CDD5DC",
    color: "rgba(51, 52, 61,0.8)",
    "&:hover": {
      border: "solid 1px #2F6EE9 !important",
      backgroundColor: `#2F6EE9 !important`,
      color: `${theme.palette.white} !important`,
    },
  },
  miniLoader: {
    marginLeft: "1vw",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
  },
  listContainer: {
    backgroundColor: theme.palette.white,
    // margin: '0 calc(24px + 1vw)',
    border: "solid 1px rgba(0, 0, 0, 0.05)",
    boxShadow: "0px 1px 4px 0 rgba(92, 101, 132, 0.18)",
    borderRadius: "10px",
    height: "fit-content",
  },
  listHeader: {
    color: theme.palette.headerGray,
    fontSize: "20px",
    fontWeight: "300",
    padding: "2.5vh 2vw",
    display: "flex",
    justifyContent: "space-between",
  },
  searchContainer: {
    margin: "0px calc(24px + 1vw) 20px calc(24px + 1vw)",
    display: "flex",
    justifyContent: "space-between",
    paddingTop: "30px",
    "@media screen and (max-width: 1280px) and (min-height: 577px) and (max-height: 577px)":
      {
        marginBottom: "10px !important",
        paddingTop: "15px",
      },
  },
  searchField: {
    // boxShadow: '0 0 29px 0 rgb(0 0 0 / 7%)',
    borderRadius: "6px",
    border: "none",
    backgroundColor: "#ecf0f2 !important",
    height: "100%",
    "&$focused": {
      backgroundColor: "#ecf0f2",
    },
    "&:hover": {
      backgroundColor: "#ecf0f2",
    },
  },
  searchInput: {
    padding: "1vh 1vw",
    fontSize: "11px",
    [theme.breakpoints.up("md")]: {
      fontSize: "12px",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "14.5px",
    },
  },
  filterButton: {
    padding: "0 1vw",
    boxShadow: "0px 1px 4px 0 rgb(92 101 132 / 18%)",
    borderRadius: "20px",
    backgroundColor: theme.palette.white,
    display: "flex",
    color: theme.palette.headerGray,
    fontWeight: "500",
    marginLeft: "1vw",
    cursor: "pointer",
  },
  filterActive: {
    backgroundColor: theme.palette.blue,
    color: theme.palette.white,
  },
  docStatus: {
    // fontSize: '11.5px',
    color: "#30b283",
    backgroundColor: "#ebf9f5",
    borderRadius: "15px",
    padding: "1vh 1vw",
    display: "flex",
    width: "fit-content",
  },
  dot: {
    borderRadius: "50%",
    width: "4px",
    height: "4px",
    marginRight: "6px",
  },
  fileName: {
    width: "8vw",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    cursor: "pointer",
    color: theme.palette.blue,
  },
  filterMenu: {
    boxShadow: "0 0 49px 0 rgba(71, 71, 71, 0.15)",
    border: " solid 1px rgba(0, 0, 0, 0.1)",
    borderRadius: "10px",
    marginTop: "1vh",
    width: "13%",
    padding: "2vh 0",
  },
  deleteButton: {
    boxShadow: " 0px 1px 4px 0 rgba(92, 101, 132, 0.18)",
    borderRadius: "5px",
    border: "solid 1px rgba(0, 0, 0, 0.1)",
    display: "flex",
    color: "#646884",
    fontWeight: "500",
    fontSize: "12px",
    padding: "0 1vw",
    marginLeft: "1vw",
    cursor: "pointer",
  },
  downloadButton: {
    display: "flex",
    color: theme.palette.white,
    fontWeight: "normal",
    borderRadius: "20px",
    boxShadow: " 0px 1px 4px 0 rgba(92, 101, 132, 0.18)",
    border: "solid 1px rgba(0, 0, 0, 0.1)",
    backgroundColor: theme.palette.black1,
    fontSize: "10px",
    padding: "0 1vw",
    marginLeft: "1vw",
    cursor: "pointer",
  },
  accordion: {
    boxShadow: "none",
    padding: "0 !important",
    minHeight: "0 !important",
    width: "100%",
    color: theme.palette.headerGray,
    fontSize: "12px !important",
    fontWeight: "500",
  },
  menuItem: {
    backgroundColor: theme.palette.white,
    padding: "0 1vw !important",
    paddingBottom: "1vh !important",
    margin: "0",
    "&:last-child": {
      paddingBottom: "0vh !important",
    },
  },
  noMarginPadding: {
    margin: "0 !important",
    padding: "0 !important",
  },
  menuExpanded: {
    margin: "0 !important",
    padding: "0 !important",
    paddingBottom: "1vh !important",
  },
  filterOption: {
    display: "flex",
    padding: "0.5vh 0",
    color: "#8e92a9",
    fontWeight: "normal",
    fontSize: "11px",
    "&:first-child": {
      paddingTop: "0vh !important",
    },
  },
  expandIcon: {
    color: theme.palette.headerGray,
    fontSize: "12px",
  },
  docCategoryContainer: {
    boxShadow: "0px 1px 4px 0 rgba(92, 101, 132, 0.18)",
    border: "solid 1px rgba(0, 0, 0, 0.05)",
    backgroundColor: theme.palette.white,
    borderRadius: "10px",
    margin: "1vh 2vw 20px 2vw",
    fontSize: "12px",
    color: "#464962",
    fontWeight: "500",
    padding: "0 2vw",
    height: "13vh",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
  },
  configHeading: {
    margin: "10px 2vw 20px 2vw",
    color: theme.palette.headerGray,
  },
  categoryOption: {
    fontSize: "11.5px",
    color: "#9ea2bb",
    marginRight: "1.5vw",
    cursor: "pointer",
    margin: "1.5vh 0 0 0",
    fontWeight: "normal",
    display: "flex",
  },
  categoryCheck: {
    width: "11px",
    height: "11px",
    border: "solid 1px rgba(0, 0, 0, 0.2)",
    borderRadius: "3px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    marginRight: "5px",
  },
  categorySelected: {
    width: "5px",
    height: "5px",
    backgroundColor: theme.palette.darkYellow,
    alignSelf: "center",
  },
  table: {
    tableLayout: "fixed",
  },
});

export const documentStyles = (theme) => ({
  clockBg: {
    backgroundColor: "rgba(0,0,0,0.7)",
    zIndex: "100",
    width: "100%",
    height: "100%",
    position: "absolute",
    textAlign: "center",
    height: "calc(100% - 120px)",
    color: "white",
  },
  selectedColumn: {
    fontWeight: "bold",
  },
  expandedTable: {
    height: "calc(35% - 1vh)",
    borderRadius: "4px",
    border: "solid 1px black",
    marginTop: "1vh",
    marginRight: "8px",
  },
  holdStatus: {
    borderRadius: "15px",
    padding: "0.5vh 1vw",
    display: "flex",
    width: "fit-content",
    fontWeight: "500",
  },
  lockedBackground: {
    backgroundColor: "rgba(0,0,0,0.6)",
    zIndex: "9999",
    width: "100%",
    height: "100%",
    position: "absolute",
    textAlign: "center",
    color: "white",
  },
  noDetailFound: {
    height: "80%",
    textAlign: "center",
  },
  noDetailText: {
    // backgroundColor: theme.palette.lightGray,
    //  borderRadius:'15px'
  },
  noResults: {
    color: "#172B4D",
    fontWeight: "500",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    textAlign: "center",
  },
  selectLabel: {
    display: "flex",
    color: "#5c5d64",
    //fontSize: '12.5px',
    marginBottom: "0.8vh",
    fontWeight: "400 !important",
  } /*Styles for input*/,
  textFieldRoot: {
    border: "none",
    fontWeight: "normal !important",
    padding: "1vh 1vw !important",
    border: "1px solid #8A8886",
    color: "#33343D !important",
  },
  textFieldRootFocus: {
    border: "solid 1px green !important",
    fontWeight: "normal !important",
    padding: "1.5vh 1vw !important",
  },

  textFieldInput: {
    fontSize: "12px !important",
    fontWeight: "normal !important",
  },
  autoCompleteInput: {
    padding: "0 !important",
    fontWeight: "normal !important",
    fontSize: "12px !important",
  },
  autoOptions: {
    backgroundColor: "white !important",
    padding: "1vh 1vw 0 1vw !important",
    borderRadius: "0px",
    color: "#646884",
    fontSize: "12px !important",
    [theme.breakpoints.up("md")]: {
      fontSize: "12px !important",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "14.5px !important",
    },
  },
  autoClear: {
    display: "none",
  },
  autoPaper: {
    boxShadow: "0px 19px 27px 0 rgba(71, 71, 71, 0.09)",
    border: "solid 1px rgba(0, 0, 0, 0.1)",
    borderRadius: "5px",
  },
  disabledText: {
    cursor: "not-allowed",
    backgroundColor: "lightGray",
  },
  disabledTextWhite: {
    cursor: "pointer !important",
  },
  holdStatusCont: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: "2vh",
    minHeight: "25px",
  },
  putOnHold: {
    color: "#33343D",
    fontWeight: "400",
    display: "flex",
    height: "100%",
  },
  tableContainert: {
    overflow: "hidden",
    // flex: '1',
    // margin: '40px 0 0 0',
    height: "90%",
    // marginTop: '1vh',
    maxWidth: "100%",
    borderBottom: "0.75px solid rgba(138, 136, 134,0.4) !important",

    //padding: '0 2vw'
  },
  docDrawer: {
    width: "75%",
  },
  accSContent: {
    color: "#3C4257",
    margin: "0 !important",
    "&$content": {
      margin: "0 !important",
    },
  },
  accSExpandIcon: {
    padding: "0 1vw !important",
  },
  accSRoot: {
    padding: "1vh 1vw !important",
    borderRadius: "0px !important",
    minHeight: "0px !important",
    borderRadius: "2px !important",
    border: "1px solid #8A8886",
    boxShadow: "none !important",
  },
  accSExpanded: {
    // borderBottom: '1px solid #B7B8B9',
    color: "#3C4257",
    //  padding: '1vh 0 !important',
    margin: "0 0 !important",
    border: "0",
    minHeight: "0px !important",
    backgroundColor: "#EDF3FF",
  },
  accRoot: {
    height: "50% !important",
    display: "flex",
    flexDirection: "column",
    borderRadius: "2px !important",
    border: "1px solid #8A8886",
    boxShadow: "none !important",
  },
  collapseHeader: {
    borderRadius: "2px",
    border: "1px solid #8A8886",
    color: "#3C4257",
    marginBottom: "1.5vh",
    fontWeight: "400",
    cursor: "pointer",
    //  height: '50%',
    overflow: "scroll",
  },
  activeCollapseHeader: {
    height: "50%",
    // backgroundColor: '#EDF3FF',
    borderRadius: "2px",
    border: "1px solid #8A8886",
    color: "#3C4257",
    marginBottom: "1.5vh",
    fontWeight: "400",

    cursor: "pointer",
    overflow: "scroll",
  },
  tab: {
    // padding: '1vh 1vw',
    width: "100%",
    display: "flex",
    justifyContent: "space-between",
  },
  activeTab: {
    width: "100%",
    // padding: '0 1vw',
    backgroundColor: "#EDF3FF",
    display: "flex",
    justifyContent: "space-between",
    zIndex: "10",
    //position: 'fixed'
  },
  collapseData: {
    backgroundColor: theme.palette.white,
    height: "90% !important",
    padding: "1vh 1vw",
  },
  tablet: {
    //borderRadius: '10px'
    //tableLayout: 'fixed'
  },
  qrKey: {
    display: "flex",
    marginBottom: "1vh",
    width: "40%",
    fontWeight: "500",
    color: theme.palette.black1,
  },

  qrData: {
    color: theme.palette.headerGray,
    margin: "2vh 2vw",
    wordBreak: "break-all",
    height: "100%",
    overflowY: "scroll",
  },
  tableRoott: {
    // border: 'solid 1px rgba(0, 0, 0, 0.1)',
    maxHeight: "100%",
    // borderRadius: '10px'
  },
  collapseWrapper: {
    // height: 'auto !important',
    overflow: "scroll",
  },
  tableRowt: {
    "&:hover": {
      boxShadow: "none !important",
    },
  },
  tableHeadert: {
    backgroundColor: theme.palette.black1,
    color: `#000000 !important`,
    borderRight: " solid 1px rgba(0, 0, 0, 0.1)",
  },
  tableCellt: {
    borderRight: "0.75px solid rgba(138, 136, 134,0.4)",
    fontWeight: "normal !important",
    fontSize: "12px !important",

    boxShadow: "none !important",
    "&:hover": {
      boxShadow: "none !important",
    },
    "&:last-child": {
      borderRight: "0.75px solid rgba(138, 136, 134,0.4) !important",
    },

    // borderRight: ' solid 1px rgba(0, 0, 0, 0.1)'
  },
  tableCellData: {
    border: "0.75px solid #8A8886",
    borderRadius: "4px",
    padding: "1vh",
  },
  content: {
    flexGrow: 1,
    backgroundColor: theme.palette.lighGray,
    display: "flex",
    position: "relative",
    height: "100%",
  },
  documentContainer: {
    width: "65%",
  },
  expansionPanel: {
    width: "100%",
    backgroundColor: theme.palette.darkBlue,
    color: theme.palette.white,
    boxShadow: "0 2px 6px 0 rgba(16, 119, 255,  0.7)",
  },
  expandIcon: {
    color: theme.palette.white,
  },
  fullWidth: {
    width: "100%",
  },
  tableKey: {
    pointerEvents: "none",
    backgroundColor: theme.palette.brownishGray,
  },
  formField: {
    paddingTop: 0,
    marginTop: 0,
    marginBottom: 0,
  },
  tableHeader: {
    paddingTop: 0,
    marginTop: 0,
    marginBottom: 0,
    pointerEvents: "none",
  },
  headerField: {
    backgroundColor: theme.palette.coolGray2,
    fontWeight: "bold",
  },
  table: {
    width: "100%",
    padding: "0vh 1vw",
  },
  drawer: {
    [theme.breakpoints.up("sm")]: {
      width: "16%",
      flexShrink: 0,
    },
  },
  thumbnailContainer: {
    display: "flex",
    flexDirection: "column",
    height: "64px",
    backgroundColor: theme.palette.white,
    justifyContent: "center",
    borderRadius: "5.3px",
  },
  formSubmitContainer: {
    display: "flex",
    margin: "6vh 2vw",
    justifyContent: "center",
  },
  pageAction: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "5vh",
  },

  menuButton: {
    marginRight: theme.spacing(2),
    [theme.breakpoints.up("sm")]: {
      display: "none",
    },
  },

  documentDrawer: {
    border: 0,
    backgroundColor: theme.palette.darkBlue,
    width: "100%",
    height: "270px",
  },

  sidebarFlex: {
    height: "calc(100vh - 64px)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  columnFlex: {
    display: "flex",
    flexDirection: "column",
  },
  button: {
    color: theme.palette.white,
    fontSize: "16px",
    fontFamily: "Roboto",
    backgroundColor: theme.palette.blue,

    [theme.breakpoints.between("sm", "md")]: {
      width: "20.6vw",
    },
    [theme.breakpoints.up("md")]: {
      width: "11.6vw",
    },
    marginBottom: "2vh",
    marginLeft: "1vw",
    height: "44px",
  },

  submitButton: {
    color: theme.palette.white,
    fontSize: "16px",
    fontFamily: "Roboto",
    backgroundColor: theme.palette.blue,

    [theme.breakpoints.between("sm", "md")]: {
      width: "20.6vw",
    },
    [theme.breakpoints.up("md")]: {
      width: "11.6vw",
    },
    marginBottom: "2vh",
    marginLeft: "1vw",
    height: "44px",
    marginTop: "4vh",
  },
  cancelButton: {
    color: theme.palette.coolGray,
    fontSize: "16px",
    fontFamily: "Roboto",
    backgroundColor: theme.palette.dark,

    [theme.breakpoints.between("sm", "md")]: {
      width: "20.6vw",
    },
    [theme.breakpoints.up("md")]: {
      width: "11.6vw",
    },
    marginBottom: "2vh",
    marginLeft: "1vw",
    height: "44px",
    elevation: 0,
  },
  sidebarFooter: {
    justifyContent: "space-between",
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    color: theme.palette.white,
    fontSize: "12px",
  },
  outerLoader: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "400px",
  },
  progress: {
    color: theme.palette.red,
  },
  images: {
    width: "100%",
    transformOrigin: "0 0",
  },
  thumbnails: {
    height: "auto",
    width: "50px",
    maxHeight: "58px",
  },
  imageName: {
    fontSize: "10px",
    color: theme.palette.white,
    textAlign: "center",
  },
  imageDiv: {
    width: "65%",
    fontSize: "18px",
    height: "100vh",
    position: "relative",
    // flex: '2'
    //marginTop: 'calc(30px + 2vh)'
  },
  formDiv: {
    width: "calc(35% - 16px - 3vw) !important",
    backgroundColor: theme.palette.white,
    display: "flex",
    flexDirection: "column",
    margin: "0 8px",
    padding: "2vh 1.5vw",
    boxShadow: "0px 0px 10px rgba(0, 0, 0, 0.19)",
    border: "1px solid rgba(0, 0, 0, 0.6)",
    borderRadius: "4px",
  },
  listGutter: {
    paddingLeft: "0px",
    paddingRight: "0px",
    marginLeft: "0px !important",
  },
  tabContainer: {
    padding: "0 2vw ",
    backgroundColor: "#f8f8f8",
    borderBottom: "solid 1px rgba(0,0,0,0.1)",
    color: theme.palette.headerGray,
  },
  activeThumbnail: {
    height: "64px",
    width: "50px",
    border: "4px solid #9097a2",
    borderRadius: "5.3px",
  },
  docHeader: {
    color: theme.palette.white,
    fontSize: "18px",
  },
  navbarContainer: {},
  zoomContainer: {
    position: "fixed",
    top: "50%",
    right: "12%",
    width: "46px",
    height: "120px",
    backgroundColor: "rgba(62, 70, 78, 0.6)",
    opacity: "0.9",
    borderRadius: "8px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    alignItems: "center",
  },
  pageNo: {
    position: "absolute",
    top: "5%",
    right: "10%",
    padding: "4px",
    backgroundColor: "rgba(0,0,0, 0.6)",
    opacity: "1",
    borderRadius: "8px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    alignItems: "center",
    color: theme.palette.white,
  },
  dropDownIcon: {
    color: theme.palette.coolGray2,
    position: "absolute",
  },
  svg: {
    cursor: "pointer",
  },
  thumbnailIcons: {
    position: "absolute",
    top: "50%",
    left: "33%",
  },
  closeIcon: {
    display: "flex",
    flexDirection: "row-reverse",
    color: theme.palette.coolGray,
  },
  loading: {
    top: "40%",
    right: "45%",
    position: "fixed",
  },
  imageContainer: {
    height: "100vh",
    width: "100%",
    // width: 'inherit',
    //  position: 'fixed',
    //  backgroundColor: theme.palette.white,
    borderRight: "solid 1px rgba(0,0,0,0.1)",
  },
  loaderDiv: {
    backgroundColor: theme.palette.dark,
    height: "100%",
    justifyContent: "center",
    flexDirection: "column",
    display: "flex",
  },
  headerContainer: {
    display: "flex",
    justifyContent: "space-between",
    padding: "1vw",
  },
  formStyle: {
    height: "100%",
    backgroundColor: theme.palette.white,
    padding: "1.5vh 1vw 0 2vw",
    boxShadow: "0px 0px 10px rgba(0, 0, 0, 0.19)",
    overflowY: "scroll",
    overflowX: "hidden",
    border: "1px solid rgba(0, 0, 0, 0.6)",
  },
  tabRoot: {
    padding: "0",
    minWidth: "fit-content",
    fontSize: "12px",
    marginRight: "2vw",
  },
  navIcons: {
    marginRight: "2vw",
    cursor: "pointer",
  },
  textContainer: {
    display: "flex",
    flexDirection: "column",
    width: "100% !important",
    borderRadius: "4px",
    border: `solid 1px ${theme.palette.battleShipGray}`,
  },
});

export const inputStyles = (theme) => ({
  inputContainer: {
    background: "#FFFFFF 0% 0% no-repeat padding-box",
    border: "1px solid #D9D9D9",
    borderRadius: "6px",
    padding: "0.5vh 0vw 0.5vh 1vw",
    margin: "1vh 0 0 0",
    width: "88%",
    display: "flex",
    justifyContent: "space-between",
  },
  highlightedInput: {
    border: "solid 2px #A31ACB",
  },
  currentField: {
    border: "solid 2px #FC9A07",
  },
  disabledDocField: {
    cursor: "pointer !important",
  },
  mandatory: {
    color: "#e45f5f",
  },
  fieldPageNo: {
    color: "black",
    fontSize: "10px",
    borderRadius: "12px",
    backgroundColor: "lightGray",
    padding: "2px 6px",
    marginRight: "1vw",
    width: "calc(100% - 2vw)",
    textAlign: "center",
    cursor: "pointer",
    border: "solid 1px darkGray",
    "&:hover": {
      backgroundColor: "#f5f5f5 !important",
      // border: 'solid 1px #157fff',
    },
  },
  high: {
    color: "#2fb183",
    fontSize: "10px",
    borderRadius: "12px",
    backgroundColor: "#ebf9f5",
    padding: "2px 1vw",
    marginRight: "1vw",
    fontWeight: "bold",
  },
  low: {
    color: "#e45f5f",
    fontSize: "10px",
    borderRadius: "12px",
    backgroundColor: "#fde9e9",
    padding: "2px 1vw",
    marginRight: "1vw",
  },
  medium1: {
    fontSize: "10px",
    borderRadius: "12px",
    backgroundColor: "rgba(255, 204, 24,0.3)",
    padding: "2px 1vw",
    marginRight: "1vw",
  },
  medium2: {
    fontSize: "10px",
    borderRadius: "12px",
    backgroundColor: "rgba(234, 156, 39,0.3)",
    padding: "2px 1vw",
    marginRight: "1vw",
  },
  item: {
    display: "flex",
    textOverflow: "ellipsis",
    overflow: "hidden",
    whiteSpace: "nowrap",
  },
  lowConfidence: {
    border: "1px solid #ea4335",
  },
  fieldIpContainer: {
    width: "calc(100% - 2.5vw) !important",
  },
  invoiceLabel: {
    fontWeight: "500",
    color: "#5c5d64",
    fontWeight: "400",
    width: "92%",
  },
  input: {
    width: "calc(92% - 1vw)",
    paddingRight: "1vw",
  },
  tinput: {
    width: "calc(70% - 1vw)",
  },
  inputRoot: {
    color: "#33343D",
    fontWeight: "500",
  },
  select: {
    backgroundColor: "white !important",
    "&:focus": {
      backgroundColor: "yellow",
    },
  },
});

export const headerStyles = (theme) => ({
  header: {
    display: "flex",
    justifyContent: "space-between",
    color: theme.palette.blue,
    fontSize: "13px",
    height: "50px",
    fontWeight: "500",
    position: "relative",
  },
  batchId: {
    fontWeight: "500",
    backgroundColor: theme.palette.mustard,
    borderRadius: "8px",
    padding: "4px 1vw",
    marginLeft: "2vw",
    color: "black",
    display: "flex",
  },
  externalBatchId: {
    fontWeight: "500",
    backgroundColor: "lightGray",
    borderRadius: "8px",
    padding: "4px 1vw",
    marginRight: "1vw",
    marginLeft: "0.5vw",
  },
  helpBtn: {
    cursor: "pointer",
    color: "#33343D",
    fontWeight: "600",
    backgroundColor: "#FDCC43",
    padding: "4px 1vw",
    borderRadius: "16px",
    width: "fit-content",
    margin: "0 1vw 0 0",
    height: "fit-content",
  },
  pageHeading: {
    boxShadow: "0px -1px 20px rgba(0, 0, 0, 25%)",
    color: "#000000",
    fontWeight: "500",
    width: "55%",
    display: "flex",
    justifyContent: "center",
    borderBottom: "solid 1px rgba(0,0,0,0.1)",
  },
  uploadButton: {
    color: theme.palette.blue,
    backgroundColor: "white",
    border: `dashed 1px ${theme.palette.blue}`,
    borderRadius: "6px",
    fontWeight: "500",
    padding: "1vh 1vw",
    width: "max-content",
    cursor: "pointer",
    fontSize: "12px !important",
    "@media (min-width: 1440px)": {
      fontSize: "12px !important",
    },
    "@media (min-width: 1280px) and (max-height: 650px)": {
      fontSize: "10px !important",
    },
    "@media (min-width: 1680px)": {
      fontSize: "13px !important",
    },
    "@media (min-width: 1920px)": {
      fontSize: "14.5px !important",
    },
    "&:hover": {
      backgroundColor: `rgba(21, 127, 255, 0.2) !important`,
    },
  },
  reviewStats: {
    color: theme.palette.blue,
    borderRadius: "10px",
    // color: 'white',
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    padding: "4px 0",
    fontWeight: "normal",
    marginRight: "1.5vw",
  },
  pageNav: {
    cursor: "pointer",
  },
  disPageNav: {
    cursor: "not-allowed",
    color: "lightGray",
  },
  stopReview: {
    marginLeft: "8px",
    color: theme.palette.red,
  },
  fileCount: {
    backgroundColor: "#FDCC43",
    color: "black",
    borderRadius: "5px",
    padding: "0.5vw",
    marginLeft: "2vw",
    height: "fit-content",
  },
  reviewFiles: {
    marginLeft: "1vw",
  },
  pass: {
    fontWeight: "500",
    color: theme.palette.green,
    "&:hover": {
      color: "white",
      backgroundColor: `${theme.palette.green} !important`,
    },
  },
  fail: {
    fontWeight: "500",
    color: theme.palette.red,
    "&:hover": {
      color: "white",
      backgroundColor: `${theme.palette.red} !important`,
    },
  },
  fullDocName: {
    maxWidth: "80%",
  },
  fileName: {
    // width: '8vw',
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    marginLeft: "2vw",
    maxWidth: "100%",
  },
  editTableActions: {
    display: "flex",
    position: "absolute",
    width: "55%",
    top: "80%",
    zIndex: "1",
    justifyContent: "center",
  },
  editTable: {
    border: "solid 0.5px lightgray",
    backgroundColor: "white",
    display: "flex",
    padding: "1vh 1vw",
  },
  navButton: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    marginLeft: "2vw",
  },
  footer: {
    position: "absolute",
    bottom: "1%",
    boxShadow: "0px -1px 20px rgba(0, 0, 0, 25%)",
    padding: "2vh 1vw",
    background: theme.palette.white,
    display: "flex",
    justifyContent: "flex-end",
    width: "calc(100% - 2vw)",
    height: "calc(60px - 4vh)",
  },
  goBack: {
    cursor: "pointer",
    color: theme.palette.black1,
    fontWeight: "400",
    marginRight: "1vw",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    zIndex: "1500",
  },
  docName: {
    color: "#000000",
    fontWeight: "500",
    width: "55%",
    display: "flex",
    justifyContent: "center",
  },
  actionItems: {
    border: "1px solid #D6D6D6",
    borderRadius: "5px",
    color: theme.palette.black1,
    height: "fit-content",
    padding: "0.5vw",
    display: "flex",
    fontWeight: "500",
    cursor: "pointer",
    marginLeft: "1vw",
    "&:last-child": {
      marginRight: "1vw",
    },
  },
  docType: {
    fontSize: "11px",
    backgroundColor: theme.palette.darkYellow,
    color: theme.palette.black1,
    borderRadius: "8px",
    padding: "0 1vw",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
  },
  info: {
    fontSize: "12px",
    color: theme.palette.headerGray,
    display: "flex",
    width: "max-content",
  },
  rowLink: {
    cursor: "pointer",
    // textDecoration: 'underline',
    fontWeight: "600",
    width: "12vw",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    cursor: "pointer",
    color: "#314059",
  },

  status: {
    backgroundColor: "#fde9e9",
    border: "solid 1px rgba(234, 67, 53, 0.1)",
    borderRadius: "10px",
    padding: "1vh 1vw",
    fontSize: "12px",
    color: "#3d3f52",
  },
  timer: {
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    fontSize: "18px",
  },
  imageHeader: {
    // boxShadow: '0px 12px 29px 0 rgba(0, 0, 0, 0.1)',
    backgroundColor: theme.palette.white,
    borderBottom: "solid 1px rgba(0,0,0,0.1)",
    padding: "1vh",
    width: "100%",
    height: "30px",
    zIndex: "1",
    left: "35%",
    display: "flex",
  },
  searchContainer: {
    backgroundColor: theme.palette.bgGray,
    borderRadius: "5px",
    width: "25%",
  },
  input: {
    padding: "1vh 1vw",
  },
  searchInput: {
    fontSize: "12px",
    border: "none !important",
    borderRadius: "5px",
    color: "#8e92a9",
    "&:hover": {
      backgroundColor: theme.palette.bgGray,
    },
    "&$focused": {
      backgroundColor: theme.palette.bgGray,
    },
  },
  timerIcon: {
    color: theme.palette.blue,
    marginRight: "1.2vh",
    cursor: "pointer",
  },
  icon: {
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    borderRight: "1px solid #E7E8F2",
    padding: "0.5vw",
    "&:last-child": {
      borderRight: "none",
    },
  },
  iconContainer: {
    display: "flex",
    border: "1px solid #E7E8F2",
    borderRadius: "6px",
    backgroundColor: theme.palette.white,
    height: "fit-content",
  },
});

export const navbarStyles = (theme) => ({
  navbar: {
    width: "calc(10% - 8px - 18px)",
    backgroundColor: theme.palette.white,
    marginLeft: "10px",
    marginRight: "8px",
    display: "flex",
    flexDirection: "column",
    padding: "2vh 4px",
    boxShadow: "inset 0px 0px 2px rgba(0, 0, 0, 0.25)",
    height: "calc(100% - 100px)",
    overflowY: "scroll",
  },
  mDrawer: {
    width: "70% !important",
    padding: "3% 3%",
  },
  pageDivider: {
    width: "90%",
    marginBottom: "1vh",
    borderBottom: "dashed 2px",
  },
  qcIcon: {
    position: "absolute",
    top: "5%",
    right: "10%",
  },
  attIcon: {
    position: "absolute",
    top: "5%",
    left: "10%",
  },
  strategyIcon: {
    position: "absolute",
    bottom: "27%",
    right: "10%",
    borderRadius: "6px",
    padding: "3px 7px",
    backgroundColor: "#157fff",
    color: "white",
  },
  log: {
    fontSize: "12px",
    color: theme.palette.headerGray,
    marginBottom: "2px",
  },
  logList: {
    listStyleType: "circle",
    margin: "0",
    padding: "0",
  },
  thumbnailContainer: {
    border: "1px solid rgba(138, 136, 134, 0.9)",
    height: "120px",
    width: "80px",
    padding: "0",
    fontSize: "11px",
    color: theme.palette.headerGray,
    cursor: "pointer",
    position: "relative",
    // backgroundColor: 'rgba(0,0,0,0.1)',
    paddingBottom: "3px",
  },
  activePage: {
    border: `solid 2px ${theme.palette.blue}`,
  },
  thumbnail: {
    width: "calc(100% - 16px)",
    maxHeight: "100%",
    maxHeight: "100%",
    margin: "8px 4px",
    marginTop: "14px",
  },

  imageName: {
    color: theme.palette.headerGray,
    fontSize: "11px",
    textAlign: "center",
    marginRight: "1vh",
    marginLeft: "-8px",
    marginRight: "-8px",
  },
  docName: {
    color: theme.palette.headerGray,
    fontSize: "11px",
    textAlign: "center",
    marginBottom: "2vh",
    width: "100%",
    overflow: "hidden",
  },
});

export const classificationStyles = (theme) => ({
  pageDivider: {
    height: "90%",
    marginBottom: "1vh",
    borderLeft: "dashed 1px",
    height: "80px",
  },
  disabledCr: {
    backgroundColor: "white",
    filter: "brightness(0.7)",
    pointerEvents: "none",
  },
  strategyMenu: {
    marginTop: "1vh",
  },
  strategyItem: {
    padding: "0.2vh",
    "&:hover": {
      backgroundColor: "#383838",
    },
  },
  disableCrMsg: {
    position: "absolute",
    height: "100%",
    width: "100%",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    top: "0",
  },
  fileInfo: {
    color: "gray",
    marginBottom: "1vh",
  },
  dragger: {
    width: "5px",
    cursor: "ew-resize",
    padding: "4px 0 0",
    borderTop: "1px solid #ddd",
    position: "absolute",
    top: 0,
    left: 0,
    bottom: 0,
    zIndex: "100",
    backgroundColor: "#f4f7f9",
  },
  hygieneContainer: {
    position: "fixed",
    marginTop: "1vw",
    zIndex: "1",
    backgroundColor: "lightGray",
    borderRadius: "8px",
    marginLeft: "1vw",
  },
  minimizeCont: {
    position: "fixed",
    marginTop: "1vw",
    right: "1vw",
    zIndex: "1",
    backgroundColor: "lightGray",
    borderRadius: "8px",
  },
  icon: {
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    borderRight: "1px solid #E7E8F2",
    padding: "0.5vw",
    "&:last-child": {
      borderRight: "none",
    },
  },
  zoomDrawer: {
    position: "absolute !important",
    // width: '40% !important',
    height: "100%",
  },
  clockBg: {
    backgroundColor: "rgba(0,0,0,0.7)",
    zIndex: "100",
    width: "100%",
    height: "100%",
    position: "absolute",
    textAlign: "center",
    height: "calc(100% - 120px)",
    color: "white",
  },

  pageDivContainer: {
    height: "150px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    //padding: '0 1.5vw',
    position: "relative",
  },
  splitIcon: {
    position: "absolute",
    top: "calc(50% - 16px)",
    left: "calc(50% - 10px)",
    // zIndex: '1',
    backgroundColor: "white",
  },
  mergeIcon: {
    position: "absolute",
    bottom: "25%",
    left: "30%",
    backgroundColor: "white",
  },
  qcIcon: {
    position: "absolute",
    top: "5%",
    right: "10%",
  },
  attIcon: {
    position: "absolute",
    top: "5%",
    left: "10%",
  },
  strategyIcon: {
    position: "absolute",
    top: "5%",
    right: "10%",
    borderRadius: "6px",
    padding: "3px 7px",
    backgroundColor: "#157fff",
    color: "white",
  },
  thumbnailContainer: {
    border: "1px solid rgba(138, 136, 134, 0.9)",
    height: "150px",
    width: "120px",
    padding: "0",
    fontSize: "11px",
    color: theme.palette.headerGray,
    cursor: "pointer",
    position: "relative",
    backgroundColor: "white",
    paddingBottom: "3px",
    margin: "0 1vw",
    borderWidth: "2px",
  },
  activePage: {
    border: `solid 2px ${theme.palette.blue}`,
  },
  thumbnail: {
    width: "calc(100% - 8px)",
    height: "calc(150px - 16px )",
    margin: "8px 4px",
    overflow: "hidden",
  },
  imageName: {
    color: theme.palette.black,
    textAlign: "center",
    marginTop: "1vw",
    padding: "4px",
    borderRadius: "6px",
    width: "fit-content",
  },
  content: {
    flexGrow: 1,
    backgroundColor: theme.palette.white,
    display: "flex",
    position: "relative",
    height: "100%",
    display: "flex",
    height: "calc(100% - 120px - 4% - 4vh)",
    padding: "2%",
    flexWrap: "wrap",
    overflowY: "scroll",
  },
});

export const statStyles = (theme) => ({
  statContainer: {
    height: "10%",
    //margin: '4vh calc(24px) 10px calc(24px)',
    display: "flex",
    /* [theme.breakpoints.down('xs')]: {
       margin: '0 calc(24px) 0 calc(24px)',
     },
     '@media screen and (max-width: 1280px) and (min-height: 577px) and (max-height: 577px)': {
       marginTop: '10px'
     },
     '@media screen and  (min-height: 800px) ': {
       marginTop: '15px'
     },
     '@media screen and  (min-height: 1200px) ': {
       marginTop: '30px'
     },*/
  },
  blurredStats: {
    // filter: 'blur(3px)',
    pointerEvents: "none",
  },
  icon: {
    marginRight: "1vw",
  },
  statCard: {
    // border: '1px solid #E7E8F2',
    border: "solid 1px #c5c6d1",
    // cursor: 'pointer',
    borderRadius: "6px",
    backgroundColor: theme.palette.white,
    flex: "1",
    margin: "0 0.5vw 0 0.5vw",
    padding: "1vh 1vw",
    color: "#33343D",
    position: "relative",
    fontWeight: "400",
    display: "flex",
    "&:last-child": {
      marginRight: "0vw",
    },
    "&:first-child": {
      marginLeft: "0vw",
    },
    /*  [theme.breakpoints.up('md')]: {
        fontSize: '13.5px',
      },
      [theme.breakpoints.up('lg')]: {
        fontSize: '18.5px',
      },
      '@media screen and  (max-width: 1280px)and (min-height: 577px)': {
        height: '15vh',
      },
      '@media screen and  (min-height: 649px) and (max-height: 764px)': {
        height: '14vh',
      },
      '@media screen and  (min-width: 1920px) and (max-height: 900px)': {
        height: '14vh',
        fontSize: '15px',
      },*/
  },
  fileCount: {
    fontWeight: "600",
    color: "#33343E",
    marginRight: "1vw",
  },
  successText: {
    color: "#34ca77",
    fontWeight: "600",
    fontSize: "13px",
    padding: "0  0 0 1vw",
    display: "flex",
    [theme.breakpoints.up("md")]: {
      fontSize: "13px",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "18.5px",
    },
  },
  failedText: {
    color: "#f04848",
    fontWeight: "600",
    fontSize: "13px",
    padding: "0  0 0 1vw",
    borderLeft: "solid 1px rgba(0,0,0,0.2)",
    marginLeft: "1vw",
    [theme.breakpoints.up("md")]: {
      fontSize: "15px",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "18.5px",
    },
  },
  subText: {
    display: "flex",
    color: "#858585",
    fontWeight: "normal",
  },
  greenText: {
    color: "#34ca77",
  },
});
