export const listStyles = (theme) => ({
  pageContainer: {
    backgroundColor: theme.palette.bgGray,
    margin: "0 calc(24px + 2vw)",
    marginTop: "60px",
    height: "calc(100% - 60px)",
    width: "100%",
  },
  wfStatus: {
    color: "#42526E",
    backgroundColor: "#DFE1E6",
    borderRadius: "3px",
    width: "fit-content",
    padding: "0 4px",
  },
  exportDocs: {
    fontSize: "12px",
    cursor: "pointer",
    color: theme.palette.black1,
    display: "flex",
    flexDirection: "row",
  },
  menuPaper: {
    maxHeight: "30%",
  },
  rowLink: {
    cursor: "pointer",
    //textDecoration: 'underline',
    fontWeight: "600",
    width: "12vw",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    cursor: "pointer",
    color: "#314059",
  },
  rowLinkDis: {
    cursor: "pointer",
    fontWeight: "500",
    width: "12vw",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    cursor: "pointer",
    color: theme.palette.headerGray,
  },
  classMenu: {
    fontSize: "11px !important",
    [theme.breakpoints.up("md")]: {
      fontSize: "12px !important",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "14.5px !important",
    },
  },
  pagination: {
    marginTop: "3vh",
    display: "flex",
    justifyContent: "flex-end",
    marginRight: "calc(24px + 1vw)",
  },
  tableCellRoot: {
    padding: "1vh 1vw !important",
  },
  disRowLink: {
    cursor: "pointer",
    textDecoration: "underline",
    fontWeight: "500",
    width: "8vw",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    cursor: "not-allowed",
    color: "gray",
  },
  percentageLine: {
    height: "3px",
    border: "none",
    margin: "0",
    borderRadius: "6px",
  },
  adConfigSection: {
    flex: "1",
    margin: "2vw 1vw",
    border: "solid 1px rgba(0, 0, 0, 0.05)",
    borderRadius: "10px",
    padding: "2vw",
  },
  percentageBar: {
    border: `none`,
    backgroundColor: "#f2f2f2",
    width: "100%",
    borderRadius: "6px",
    height: "3px",
  },
  cfScore: {
    color: theme.palette.headerGray,
    marginLeft: "8px",
  },
  newConfigButton: {
    cursor: "pointer",
    color: theme.palette.blue,
    textDecoration: "underline",
    fontSize: "13px",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    fontWeight: "500",
  },
  miniHeader: {
    color: theme.palette.black1,
    padding: "2.5vh 2vw",
    display: "flex",
    justifyContent: "space-between",
    "@media screen and  (max-width: 1280px) and (min-height: 577px) and (max-height: 577px)":
      {
        padding: "1.5vh 2vw",
      },
  },
  docListHeader: {
    margin: "0 calc(24px + 1vw) 0 calc(24px + 1vw) !important",
    padding: "0 !important",
  },
  mappingListCont: {
    //  paddingTop: '33px',
    // height: 'calc(100% - 33px)'
    backgroundColor: theme.palette.white,
  },
  selectAllDocs: {
    fontSize: "12px",
    cursor: "pointer",
    textDecoration: "underline",
    color: theme.palette.black1,
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
  },
  batchFilter: {
    backgroundColor: theme.palette.black1,
    height: "fit-content",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    padding: "1px 0",
    marginRight: "4px",
    color: theme.palette.white,
    border: "solid 1px rgba(0, 0, 0, 0.05)",
    borderRadius: "20px",
  },
  classFilter: {
    backgroundColor: theme.palette.white,
    height: "fit-content",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    padding: "0 1vh",
    marginRight: "1vw",
    boxShadow: "0px 1px 4px 0 rgba(92, 101, 132, 0.18)",
    border: "solid 2px black",
    borderRadius: "20px",
    color: theme.palette.black1,
  },
  batchFilterSelect: {
    backgroundColor: "transparent",
    color: theme.palette.white,
    fontSize: "11px",
    paddingLeft: "4px",
    fontWeight: "normal",
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
    [theme.breakpoints.up("md")]: {
      fontSize: "12px",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "14.5px",
      paddingLeft: "1vw !important",
    },
  },
  classFilterSelect: {
    backgroundColor: "transparent",
    color: theme.palette.black1,
    fontSize: "11px",
    paddingLeft: "4px",
    fontWeight: "normal",
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
    [theme.breakpoints.up("md")]: {
      fontSize: "12px",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "14.5px",
      paddingLeft: "1vw !important",
    },
  },
  batchFilterIcon: {
    color: theme.palette.white,
    right: "0 !important",
  },
  classFilterIcon: {
    color: `${theme.palette.black1} !important `,
    right: "0 !important",
  },
  configChip: {
    fontSize: "11px",
    color: theme.palette.blue,
    border: `solid 1px ${theme.palette.blue}`,
    padding: "0 !important",
    height: "fit-content",
  },
  configChipContainer: {
    fontSize: "11px",
    color: theme.palette.headerGray,
    marginLeft: "1vw",
  },
  selectedAllDocs: {
    fontSize: "11px",
    cursor: "pointer",
    borderRadius: "15px",
    padding: "0 1vw",
    color: theme.palette.black1,
    backgroundColor: "#e5e5e5",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
  },
  sortIcon: {
    marginTop: "-4px",
  },
  actionIcons: {
    color: theme.palette.blue,
    marginRight: "4px",
  },
  tableLoader: {
    padding: "14vh 0",
  },
  identifiedBtn: {
    border: "solid 1px #2d9b3d",
    backgroundColor: "#2d9b3d",
    color: theme.palette.white,
    "& $idNumber": {
      backgroundColor: theme.palette.white,
      color: "#2d9b3d",
    },
  },
  allFilesBtn: {
    border: "solid 1px black",
    backgroundColor: `${theme.palette.black1} !important`,
    color: theme.palette.white,
    "& $allNumber": {
      backgroundColor: theme.palette.white,
      color: "black",
    },
  },
  disAllFilesBtn: {
    border: "solid 1px black",
  },
  unidentifiedBtn: {
    border: "solid 1px #e83c3d",
    backgroundColor: "#e83c3d",
    color: theme.palette.white,
    "& $unIdNumber": {
      backgroundColor: theme.palette.white,
      color: "#e83c3d",
    },
  },
  feedbackBtn: {
    border: "solid 1px #ecaf2b",
    backgroundColor: "#ecaf2b",
    color: theme.palette.white,
  },
  disabledIdBtn: {
    color: theme.palette.black1,
    border: "solid 1px #2d9b3d",
    backgroundColor: theme.palette.white,
    "&:hover": {
      backgroundColor: "#2d9b3d",
      color: theme.palette.white,
      "& $idNumber": {
        backgroundColor: theme.palette.white,
        color: "#2d9b3d",
      },
      // border: 'solid 1px #157fff',
    },
  },
  disabledFdBtn: {
    color: theme.palette.black1,
    border: "solid 1px #ecaf2b",
    backgroundColor: theme.palette.white,
    "&:hover": {
      backgroundColor: "#ecaf2b !important",
      color: theme.palette.white,
    },
  },
  disabledUnIdBtn: {
    color: theme.palette.black1,
    border: "solid 1px #e83c3d",
    backgroundColor: theme.palette.white,
    "&:hover": {
      backgroundColor: "#e83c3d",
      color: theme.palette.white,
      // border: 'solid 1px #157fff',
      "& $unIdNumber": {
        backgroundColor: theme.palette.white,
        color: "#e83c3d",
      },
    },
  },
  disabledUnIdBtn1: {
    color: theme.palette.headerGray,
    // border: 'solid 1px #e83c3d',
    backgroundColor: theme.palette.white,
    border: "solid 1px #e83c3d",
  },
  idNumber: {
    color: theme.palette.white,
    backgroundColor: "#2d9b3d",
    minWidth: "30px",
    borderRadius: "3px",
    marginLeft: "1vw",
  },
  unIdNumber: {
    color: theme.palette.white,
    backgroundColor: "#e83c3d",
    minWidth: "30px",
    borderRadius: "3px",
    marginLeft: "1vw",
  },
  allNumber: {
    color: theme.palette.white,
    backgroundColor: "black",
    minWidth: "30px",
    borderRadius: "3px",
    marginLeft: "1vw",
  },
  idButtons: {
    padding: "0 1vw",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    cursor: "pointer",
    margin: "0 8px",
    borderRadius: "20px",
    //  boxShadow: '0px 1px 4px 0 rgba(92, 101, 132, 0.18)',
    fontWeight: "normal",
    minWidth: "120px",
    textAlign: "center",
  },
  miniLoader: {
    marginLeft: "1vw",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
  },

  searchContainer: {
    margin: "0px calc(24px + 1vw) 20px calc(24px + 1vw)",
    display: "flex",
    justifyContent: "space-between",
    paddingTop: "30px",
    "@media screen and (max-width: 1280px) and (min-height: 577px) and (max-height: 577px)":
      {
        marginBottom: "10px !important",
        paddingTop: "15px",
      },
  },
  searchField: {
    boxShadow: "0 0 29px 0 rgb(0 0 0 / 7%)",
    borderRadius: "20px",
    border: "none",
    backgroundColor: theme.palette.white,
    height: "100%",
  },
  searchInput: {
    padding: "1vh 1vw",
    fontSize: "11px",
    [theme.breakpoints.up("md")]: {
      fontSize: "12px",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "14.5px",
    },
  },
  filterButton: {
    padding: "0 1vw",
    boxShadow: "0px 1px 4px 0 rgb(92 101 132 / 18%)",
    borderRadius: "20px",
    backgroundColor: theme.palette.white,
    display: "flex",
    color: theme.palette.headerGray,
    fontWeight: "500",
    marginLeft: "1vw",
    cursor: "pointer",
  },
  filterActive: {
    backgroundColor: theme.palette.blue,
    color: theme.palette.white,
  },
  docStatus: {
    // fontSize: '11.5px',
    color: "#30b283",
    backgroundColor: "#ebf9f5",
    borderRadius: "15px",
    padding: "1vh 1vw",
    display: "flex",
    width: "fit-content",
  },
  dot: {
    borderRadius: "50%",
    width: "4px",
    height: "4px",
    marginRight: "6px",
  },
  fileName: {
    width: "8vw",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    cursor: "pointer",
    color: theme.palette.blue,
  },
  filterMenu: {
    boxShadow: "0 0 49px 0 rgba(71, 71, 71, 0.15)",
    border: " solid 1px rgba(0, 0, 0, 0.1)",
    borderRadius: "10px",
    marginTop: "1vh",
    width: "13%",
    padding: "2vh 0",
  },
  deleteButton: {
    boxShadow: " 0px 1px 4px 0 rgba(92, 101, 132, 0.18)",
    borderRadius: "5px",
    border: "solid 1px rgba(0, 0, 0, 0.1)",
    display: "flex",
    color: "#646884",
    fontWeight: "500",
    fontSize: "12px",
    padding: "0 1vw",
    marginLeft: "1vw",
    cursor: "pointer",
  },
  downloadButton: {
    display: "flex",
    color: theme.palette.white,
    fontWeight: "normal",
    borderRadius: "20px",
    boxShadow: " 0px 1px 4px 0 rgba(92, 101, 132, 0.18)",
    border: "solid 1px rgba(0, 0, 0, 0.1)",
    backgroundColor: theme.palette.black1,
    fontSize: "10px",
    padding: "0 1vw",
    marginLeft: "1vw",
    cursor: "pointer",
  },
  accordion: {
    boxShadow: "none",
    padding: "0 !important",
    minHeight: "0 !important",
    width: "100%",
    color: theme.palette.headerGray,
    fontSize: "12px !important",
    fontWeight: "500",
  },
  menuItem: {
    backgroundColor: theme.palette.white,
    padding: "0 1vw !important",
    paddingBottom: "1vh !important",
    margin: "0",
    "&:last-child": {
      paddingBottom: "0vh !important",
    },
  },
  noMarginPadding: {
    margin: "0 !important",
    padding: "0 !important",
  },
  menuExpanded: {
    margin: "0 !important",
    padding: "0 !important",
    paddingBottom: "1vh !important",
  },
  filterOption: {
    display: "flex",
    padding: "0.5vh 0",
    color: "#8e92a9",
    fontWeight: "normal",
    fontSize: "11px",
    "&:first-child": {
      paddingTop: "0vh !important",
    },
  },
  expandIcon: {
    color: theme.palette.headerGray,
    fontSize: "12px",
  },
  docCategoryContainer: {
    boxShadow: "0px 1px 4px 0 rgba(92, 101, 132, 0.18)",
    border: "solid 1px rgba(0, 0, 0, 0.05)",
    backgroundColor: theme.palette.white,
    borderRadius: "10px",
    margin: "1vh 2vw 20px 2vw",
    fontSize: "12px",
    color: "#464962",
    fontWeight: "500",
    padding: "0 2vw",
    height: "13vh",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
  },
  configHeading: {
    margin: "10px 2vw 20px 2vw",
    color: theme.palette.headerGray,
  },
  categoryOption: {
    fontSize: "11.5px",
    color: "#9ea2bb",
    marginRight: "1.5vw",
    cursor: "pointer",
    margin: "1.5vh 0 0 0",
    fontWeight: "normal",
    display: "flex",
  },
  categoryCheck: {
    width: "11px",
    height: "11px",
    border: "solid 1px rgba(0, 0, 0, 0.2)",
    borderRadius: "3px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    marginRight: "5px",
  },
  categorySelected: {
    width: "5px",
    height: "5px",
    backgroundColor: theme.palette.darkYellow,
    alignSelf: "center",
  },
  table: {
    tableLayout: "fixed",
  },

  createButton: {
    color: "#0052CC",
    fontSize: "13px",
    fontWeight: "500",
    cursor: "pointer",
  },
  headerCont: {
    color: theme.palette.black,
    fontSize: "16px",
    fontWeight: "500",
    padding: "0 2vw",
    backgroundColor: "#F7FAFC",
    boxShadow: "0px 1px 0px rgba(0, 0, 0, 0.25)",
  },
  listHeader: {
    display: "flex",
    justifyContent: "space-between",
    padding: "1.2% 0 10px 0",
  },
  tabRoot: {
    padding: "0",
    marginRight: "2vw",
    fontWeight: "normal",
    minWidth: "fit-content",
  },
  listContainer: {
    height: "calc(100% - 120px)",
    backgroundColor: "#F7FAFC",
  },
  actionContainer: {
    display: "flex",
    backgroundColor: "#F7FAFC",
    justifyContent: "space-between",
    margin: "10px 0 0 0",
    padding: "5px 2vw 10px 2vw",
    fontWeight: "400",
  },
  tableContainer: {
    height: "calc(100% - 150px)",
    margin: "0 2vw",
  },
  pgContainer: {
    marginTop: "2vh",
    display: "flex",
    width: "100%",
    justifyContent: "flex-end",
  },
  loaderCell: {
    boxShadow: "none !important",
    "&:hover": {
      boxShadow: "none !important",
    },
  },
});
