export const uploadStyles = (theme) => ({
  reasonTooltip: {
    padding: "0 1vw !important",
  },
  menuItemCol: {
    borderBottom: "solid 1px lightGray !important",
  },
  rangeDisplay: {
    margin: "0 8px",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
  },
  selectLabel: {
    color: theme.palette.headerGray,
    fontSize: "12.5px",
    marginBottom: "0.8vh",
    fontWeight: "500",
    [theme.breakpoints.up("md")]: {
      fontSize: "12.5px !important",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "15.5px !important",
    },
  },
  reportLink: {
    color: theme.palette.blue,
    cursor: "pointer",
    marginBottom: "0.8vh",
    textDecoration: "underline",
  },
  dateRange: {
    color: "#646884",
    // backgroundColor: theme.palette.blue,
    fontSize: "13px",
    cursor: "pointer",
    padding: "0.6vh 1vh",
    borderRadius: "7px",
    border: "solid 1px black",
    fontWeight: "500",
    display: "flex",
    marginRight: "1VW",
    fontSize: "11px !important",
    "@media (min-width: 1280px) and (max-height: 650px)": {
      fontSize: "10px !important",
    },
    "@media (min-width: 1680px)": {
      fontSize: "12.5px !important",
    },
    "@media (min-width: 1920px)": {
      fontSize: "14.5px !important",
    },
  },
  statTableContainer: {
    borderBottomRightRadius: "8px",
    borderBottomLeftRadius: "8px",
    border: "solid 1px lightGray",
  },
  teamName: {
    padding: "4px 1vw",
    marginRight: "4px",
    backgroundColor: "lightGray",
    borderRadius: "10px",
  },
  teamNameTag: {
    padding: "4px 1vw",
    marginRight: "4px",
    //border: 'solid 1px lightGray',
    borderRadius: "10px",
    color: "white",
  },
  docCount: {
    width: "fit-content",
    color: theme.palette.blue,
  },
  progressRoot1: {
    borderRadius: "2.5px",
    backgroundColor: "#E7E8F2 !important",
    height: "5px !important",
  },
  barColorPrimary: {
    backgroundColor: "rgb(51, 203, 116) !important",
  },
  email: {
    backgroundColor: "lightGray",
    padding: "4px 1vw",
    borderRadius: "15px",
    marginRight: "1vw",
    marginBottom: "4px",
  },
  inQueue: {
    border: "solid 1px #F14336 !important",
    backgroundColor: "#F14336",
    color: `${theme.palette.white} !important`,
    borderRadius: "14px",
    padding: "4px",
    width: "fit-content",
  },
  batchFilter: {
    backgroundColor: theme.palette.white,
    height: "fit-content",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    padding: "1px 0",
    marginRight: "4px",
    color: theme.palette.white,
    border: "1px solid #8A8886",
    borderRadius: "6px",
  },
  upDialog: {
    width: "70%",
    height: "80%",
  },
  progressRoot1: {
    borderRadius: "2.5px",
    backgroundColor: "#E7E8F2 !important",
    height: "5px !important",
  },
  barColorPrimary: {
    backgroundColor: "rgb(51, 203, 116) !important",
  },
  requestQuota: {
    marginLeft: "6px",
    color: theme.palette.black,
    fontWeight: "500",
    textDecoration: "underline",
    cursor: "pointer",
  },
  mappingRow: {
    border: "1px solid rgba(0, 0, 0, 0.2)",
    display: "flex",
    borderBottom: "none",
    "&:last-child": {
      borderBottom: "1px solid rgba(0, 0, 0, 0.2) !important",
    },
    "&:first-child": {
      marginTop: "1vh",
    },
  },
  mappingKey: {
    width: "20%",
    borderRight: "1px solid rgba(0, 0, 0, 0.2)",
    padding: "1vh 1vw",
    fontWeight: "500",
    backgroundColor: "#dee9ff",
  },
  mappingValue: {
    // width: '50%',
    padding: "1vh",
  },
  serverUp: {
    backgroundColor: "#34ca77",
    color: theme.palette.white,
    borderRadius: "15px",
    padding: "4px 1vw",
    width: "fit-content",
  },
  serverDown: {
    backgroundColor: "#f04848",
    color: theme.palette.white,
    borderRadius: "15px",
    padding: "4px 1vw",
    width: "fit-content",
  },
  batchFilterSelect: {
    backgroundColor: "transparent",
    color: "rgba(51, 54, 61, 0.8)",
    fontSize: "11px",
    paddingLeft: "1vw",
    fontWeight: "normal",
    fontSize: "11px !important",
    "@media (min-width: 1280px) and (max-height: 650px)": {
      fontSize: "10px !important",
    },
    "@media (min-width: 1680px)": {
      fontSize: "12.5px !important",
    },
    "@media (min-width: 1920px)": {
      fontSize: "14.5px !important",
    },
  },
  uploadLimit: {
    color: "#515570",
    fontWeight: "300",
    marginBottom: "1vh",
    marginTop: "1vh",
  },
  copyCurlBtn: {
    position: "absolute",
    right: "10px",
    display: "flex",
  },
  workflowHighlight: {
    color: "#FDCC43",
    fontWeight: "500",
  },
  trialInput: {
    maxWidth: "50px",
    padding: "4px",
    marginRight: "1vw",
  },
  progressRoot: {
    height: "100%",
    borderRadius: "10px",
    backgroundColor: "white",
    border: "solid 1px lightGray",
  },
  progressBar: {
    backgroundColor: "#bdd1f0",
  },
  blurredTable: {
    // filter: 'blur(3px)',
    pointerEvents: "none",
  },
  helperTooltip: {
    zIndex: "99999 !important",
    opacity: "1 !important",
    backgroundColor: "#157fff !important",
    boxShadow: "0px 1px 6px rgba(99, 128, 157, 0.4) !important",
    padding: "1vh 1vw !important",
    color: "white !important",
    fontWeight: "500 !important",
  },
  progressText: {
    position: "absolute",
    top: "0",
    left: "0",
    right: "0",
    bottom: "0",
    margin: "auto",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    textAlign: "center",
    color: "#515570",
    fontWeight: "500    ",
  },
  pageWrapper: {
    backgroundColor: theme.palette.white,
    boxShadow: "0px 0px 5px rgba(0, 0, 0, 0.2)",
    margin: "1.2% 1.5vw",
    height: "94%",
    borderRadius: "8px",
  },
  unlockMsg: {
    backgroundColor: "rgba(0,0,0,0.7)",
    color: "white",
    padding: "1vh 1vw",
    borderRadius: "20px",
    display: "flex",
  },
  configLabel: {
    color: "#646884 !important",
    marginBottom: "2px",
    marginTop: "3vh",
  },
  rejectionMsg: {
    height: "3vh",
    padding: "1vh 1vw",
    border: "1px dashed #F14336",
    backgroundColor: "rgba(241, 67, 54, 0.1)",
    borderRadius: "2.5px",
    display: "flex",
    fontWeight: "400",
    marginTop: "1%",
  },
  pgnDivider: {
    margin: "0 1vw",
    color: "lightGray",
  },
  docListingCont: {
    backgroundColor: theme.palette.white,
    boxShadow: "0px 0px 5px rgba(0, 0, 0, 0.2)",
    margin: "1.2% 1.5vw",
    height: "70%",
    paddingBottom: "4%",
    margin: "2% 0",
    borderRadius: "8px",
    ["@media (min-width: 1280px) and (max-height: 650px)"]: {
      height: "66%",
    },
  },
  mindocListingCont: {
    backgroundColor: theme.palette.white,
    boxShadow: "0px 0px 5px rgba(0, 0, 0, 0.2)",
    margin: "1.2% 1.5vw",
    height: "calc(70% - 5vh)",
    paddingBottom: "4%",
    margin: "1% 0",
    borderRadius: "8px",
    ["@media (min-width: 1280px) and (max-height: 650px)"]: {
      height: "calc(66% - 5vh)",
    },
  },
  tableFooterCell: {
    padding: "0 !important",
    zIndex: "1",
  },
  copyButton: {
    visibility: "hidden",
    marginLeft: "1vw",
  },
  copyButton1: {
    visibility: "hidden",
    marginLeft: "1vw",
  },
  filterMenu: {
    zIndex: "10",
    position: "absolute",
    right: "25%",
    marginTop: "15px",
    boxShadow: "0px 0px 10px rgba(0, 0, 0, 0.19)",
    borderRadius: "4px",
    backgroundColor: "white",
  },
  tableFooter: {
    borderTop: "solid 1px rgba(0, 0, 0, 0.05) !important",
    // borderBottom: 'solid 1px rgba(0, 0, 0, 0.05) !important',
    padding: "1.2vh 1vw",
    marginLeft: "-0.8vw",
    marginRight: "-0.8vw",
  },
  draggedColumn: {
    zIndex: "99",
  },
  miniTableHead: {
    padding: "2vh 1vw",
  },
  expandedClass: {
    boxShadow: "none !important",
    backgroundColor: "#edf3ff",
    "&:hover": {
      boxShadow: "none !important",
    },
  },
  miniTableRow: {},
  giveFeedback: {
    color: "#343841",
    border: "1px solid #2F6EE9",
    borderRadius: "6px",
    display: "flex",
    fontWeight: "500",
    cursor: "pointer",
    padding: "0 1vw",
    position: "relative",
  },
  disGiveFeedback: {
    color: "lightGray",
    cursor: "not-allowed",
    border: "1px solid lightGray",
    display: "none",
  },
  disReview: {
    filter: "contrast(0)",
    cursor: "not-allowed",
  },
  grayFeedback: {
    filter: "contrast(0)",
    pointerEvents: "none",
  },
  expandedRow: {
    boxShadow: "none !important",
    "&:hover": {
      boxShadow: "none !important",
    },
  },
  dropdown: {
    transition: theme.transitions.create(["transform"], {
      duration: theme.transitions.duration.short,
    }),
  },
  dropdownOpen: {
    transform: "rotate(-180deg)",
  },
  dropdownClosed: {
    transform: "rotate(0)",
  },
  resultCont: {
    backgroundColor: theme.palette.blue,
    color: theme.palette.white,
    borderRadius: "10px",
    textAlign: "left",
    width: "fit-content",
    padding: "1vh 3vw",
    display: "flex",
  },
  imgPreview: {
    width: "20%",
    height: "60%",
    zIndex: "99999 !important",
    opacity: "1 !important",
    backgroundColor: "#EDF3FF !important",
    boxShadow: "0px 1px 6px rgba(99, 128, 157, 0.4) !important",
    padding: "1vh 2vw !important",
    color: "#000000 !important",
    fontWeight: "500 !important",
  },
  previewPageNo: {
    color: "rgba(0,0,0,0.7)",
    backgroundColor: theme.palette.white,
    padding: "3px 1vw",
    borderRadius: "6px",
  },
  actionBtn: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    marginLeft: "1vw",
  },
  processingLoader: {
    borderRadius: "50%",
    width: "20px",
    height: "20px",
    padding: "2px",
    backgroundColor: theme.palette.white,
    border: `1px dashed #4484FF`,
    color: theme.palette.black1,
    textAlign: "center",
    fontSize: "16px",
    fontWeight: "500",
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    textTransform: "capitalize",
    cursor: "pointer",
    margin: "0 4px 0 1vw",
  },
  ocrComplete: {
    backgroundColor: "#4484FF",
  },
  calendarContainer: {
    marginTop: "30px",
    position: "absolute",
    boxShadow: "0px 0px 10px rgb(0 0 0 / 19%)",
  },
  processBtn: {
    borderRadius: "6px",
    border: "solid 1px #e3e3ef",
    padding: "0.5vh 1vw",
    color: "#667EBC",
    fontWeight: "500",
    cursor: "pointer",
    textAlign: "center",
  },
  disProcessBtn: {
    cursor: "not-allowed",
    backgroundColor: "rgba(211,211,211, 0.4)",
    color: "#838383",
    fontWeight: "400",
    border: "none !important",
    pointerEvents: "none",
  },
  sourceCont: {
    border: "1px dashed #A5C9FF",
    borderRadius: "4px",
    padding: "1vw",
    display: "flex",
  },
  switchRoot: {
    width: "35px",
    height: "20px",
  },
  switchThumb: {
    width: "13px !important",
    height: "13px !important",
  },
  instContainer: {
    color: theme.palette.black,
    padding: "0 2vw",
    fontWeight: "500",
    width: "50%",
  },
  apiInst: {
    margin: "1vh 0",
    color: "#4d4d4d",
    fontWeight: "400",
  },
  composeEmail: {
    color: "#33343D",
  },
  emailInst: {
    opacity: "0.5",
    fontWeight: "400",
    marginTop: "1vh",
  },
  apiData: {
    backgroundColor: "#3E4F6F",
    borderRadius: "4px",
    color: theme.palette.white,
    fontWeight: "400",
    padding: "2vh 1vw",
    width: "50%",
    lineHeight: "2",
    position: "relative",
  },
  uploadButton: {
    color: theme.palette.blue,
    backgroundColor: "#f8f8fb",
    border: `dashed 1px ${theme.palette.blue}`,
    borderRadius: "6px",
    fontWeight: "500",
    padding: "1vh 1vw",
    cursor: "pointer",
    marginLeft: "1vw",
    fontSize: "12px !important",
    "@media (min-width: 1440px)": {
      fontSize: "12px !important",
    },
    "@media (min-width: 1280px) and (max-height: 650px)": {
      fontSize: "10px !important",
    },
    "@media (min-width: 1680px)": {
      fontSize: "13px !important",
    },
    "@media (min-width: 1920px)": {
      fontSize: "14.5px !important",
    },
  },
  viewBatchBtn: {
    border: "none",
    backgroundColor: theme.palette.blue,
    color: theme.palette.white,
  },
  uploadButton1: {
    width: "fit-content",
    backgroundColor: "#4484FF",
    color: theme.palette.white,
    alignSelf: "center",
    marginTop: "1vh",
    fontSize: "12px !important",
    "@media (min-width: 1440px)": {
      fontSize: "12px !important",
    },
    "@media (min-width: 1280px) and (max-height: 650px)": {
      fontSize: "10px !important",
    },
    "@media (min-width: 1680px)": {
      fontSize: "13px !important",
    },
    "@media (min-width: 1920px)": {
      fontSize: "14.5px !important",
    },
  },
  mappingCell: {
    padding: "1.7vh 1vw",
  },
  container: {
    boxShadow: "none",
  },
  table: {
    tableLayout: "fixed",
  },
  batchesPerPage: {
    display: "flex",
    marginLeft: "4px",
    cursor: "pointer",
  },
  checkbox: {
    padding: "0px !important",
  },
  pageMenu: {
    marginTop: "30px !important",
    padding: "1vh 0",
  },
  columnMenu: {
    minWidth: "15%",
    marginTop: "40px !important",
    padding: "1vh 0",
    width: "15%",
    right: "0",
  },
  uploadedVia: {
    backgroundColor: "#ecf0f2",
    color: "#33343D",
    borderRadius: "4px",
    padding: "0.5vh 1vw",
    display: "flex",
    width: "fit-content",
  },
  menuBackdrop: {
    backgroundColor: "rgba(0,0,0, 0.3)",
  },
  docStatus: {
    color: "#30b283",
    // borderRadius: '15px',
    // padding: '2px 1vw',
    display: "flex",
    width: "fit-content",
    fontWeight: "500",
  },
  menuItem: {
    fontSize: "11px !important",
    [theme.breakpoints.up("md")]: {
      fontSize: "12px !important",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "14.5px !important",
    },
  },
  percentageBar: {
    border: `none`,
    backgroundColor: "#E7E8F2",
    width: "100%",
    borderRadius: "2.5px",
    height: "5px",
  },
  barContainer: {
    padding: "1vh 0vw",
    fontSize: "13px",
    width: "100%",
    marginBottom: "0vh",
  },
  percentageContainer: {
    fontSize: "13px",
    display: "flex",
    justifyContent: "flex-end",
    flexDirection: "column",
    marginLeft: "2vw",
  },
  percentageCount: {
    fontSize: "10px",
    color: theme.palette.headerGray,
    marginLeft: "8px",
  },
  percentageLine: {
    height: "5px",
    border: "none",
    margin: "0",
    borderRadius: "2.5px",
  },
  cfScore: {
    marginLeft: "1vw",
  },
  hiddenTableRow: {
    visibility: "hidden",
    borderBottom: "none !important",
    boxShadow: "none !important",
  },
  pagination: {
    marginTop: "4vh",
    display: "flex",
    justifyContent: "flex-end",
  },
  batchListCont: {
    width: "calc(60% - 6vw)",
    backgroundColor: theme.palette.white,
    height: "calc(100% - 60px)",
    padding: "30px 3vw",
    borderLeft: "solid 1px rgba(0,0,0,0.1)",
  },
  filesSelected: {
    color: theme.palette.black1,
    fontWeight: "400",
    display: "flex",
    margin: "2vh 0",
  },
  actionContainer: {
    display: "flex",
    justifyContent: "flex-end",
    margin: "1vh  -1.5vw 0 -1.5vw",
    //boxShadow: '0px -1px 20px #e7e8f2',
    padding: "1% 2vw 2% 2vw",
    // position: 'absolute',
    right: "2vw",
    bottom: "0",
  },
  uploadContainer: {
    borderRadius: "4px",
    border: "1px dashed #A5C9FF",
    cursor: "initial",
    backgroundColor: theme.palette.white,
    padding: "5% 0",
    position: "relative",
  },
  miniUploadCont: {
    padding: "1vh 1vw",
    display: "flex",
    justifyContent: "flex-start",
    borderRadius: "4px",
    border: "1px dashed #A5C9FF",
    cursor: "initial",
    backgroundColor: theme.palette.white,
    height: "30%",
    position: "relative",
  },
  tabContainer: {
    display: "flex",
    margin: "0 0 2vh 0",
    // justifyContent: 'space-between'
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "16px",
    color: theme.palette.black,
    fontWeight: "400",
    [theme.breakpoints.up("md")]: {
      fontSize: "16px",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "20.5px",
    },
  },
  headerCont: {
    margin: "1.5vh 1vw",
    display: "inline-block",
    width: "calc(100% - 2vw)",
  },
  headerContl: {
    margin: "1.5vh 1vw",
    display: "inline-block",
    width: "calc(100% - 2vw)",
    height: "6%",
  },
  fileType: {
    cursor: "pointer",
    color: "rgba(93, 110, 147, 0.5)",
    marginRight: "1vw",
    fontSize: "13px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    [theme.breakpoints.up("md")]: {
      fontSize: "13px",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "18px",
    },
  },
  selectedFileType: {
    color: theme.palette.headerGray,
    borderBottom: `solid 2px ${theme.palette.black1}`,
  },
  uploadText: {
    textAlign: "center",
    display: "flex",
    fontWeight: "500",
    color: "#515570",
    justifyContent: "center",
    marginBottom: "1vh",
  },
  uploadSubText: {
    color: "#172B4D",
    fontWeight: "400",
  },
  miniUploadText: {
    textAlign: "left",
    justifyContent: "flex-start",
    marginLeft: "2vw !important",
  },
  browse: {
    color: "#3c9dff",
    textDecoration: "underline",
    cursor: "pointer",
  },
  fileTypes: {
    color: "#666869",
    textAlign: "center",
    fontSize: "13px",
    margin: "0 0 1vh 0",
    [theme.breakpoints.up("md")]: {
      fontSize: "13px",
    },
    [theme.breakpoints.up("lg")]: {
      fontSize: "18px",
    },
  },
  fileName: {
    color: "#7d91a4",
    display: "flex",
    justifyContent: "space-between",
    width: "95%",
    marginLeft: "1vw",
    marginRight: "1.5vw",
  },
  selectConfig: {
    fontSize: "11.5px",
    color: theme.palette.headerGray,
    fontWeight: "500",
    display: "flex",
    position: "relative",
    minWidth: "10%",
  },
  uploadSource: {
    color: "#5c5d64",
    borderRadius: "90px",
    border: "solid 1px #dfe0ea",
    padding: "0.8vh 1vw",
    marginLeft: "1vw",
    fontWeight: "500",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
  },
  activeSource: {
    color: "#33343D",
    fontWeight: "600",
    backgroundColor: "#FDCC43",
    border: "none",
  },
  filesContainer: {
    width: "50%",
    color: "#636785",
    overflowY: "scroll",
    height: "65%",
    padding: "2%",
    border: "solid 1px rgba(15, 145, 210,0.4)",
    borderRadius: "10px",
  },
  progressContainer: {
    width: "100%",
    color: "#636785",
    overflowY: "scroll",
    height: "65%",
    paddingRight: "2%",
    display: "flex",
    justifyContent: "flex-start",
    flexDirection: "column",
  },
  fileList: {
    height: "70%",
  },
  fileDisplay: {
    flex: "1",
    display: "flex",
    justifyContent: "center",
    marginBottom: "2vh",
    // backgroundColor: '#f7fafd',
    borderRadius: "5px",
    // border: 'solid 1px rgba(0, 0, 0, 0.05)',
    padding: "5% 0",
  },
  file: {
    fontSize: "12px",
    width: "100%",
    overflow: "hidden",
    marginBottom: "3vh",
  },
  uploadSuccess: {
    height: "2px",
    width: "calc(100% - 2vw)",
    marginTop: "1vh",
    backgroundColor: theme.palette.blue,
    marginLeft: "1vw",
    borderRadius: "10px",
  },
  uploadClose: {
    height: "2px",
    width: "calc(100% - 2vw)",
    marginTop: "1vh",
    backgroundColor: "rgba(0, 0, 0, 0.1)",
    marginLeft: "1vw",
    borderRadius: "10px",
  },
  dialog: {
    maxHeight: "70%",
    width: "40%",
    overflow: "hidden",
  },
  dialogHeading: {
    fontSize: "16px",
    fontWeight: "500",
    color: theme.palette.headerGray,
    textAlign: "center",
  },
  dialogSubHeading: {
    fontSize: "13px",
    color: theme.palette.slateGray,
  },
  fileDialogContent: {
    overflowX: "hidden",
  },
  backdrop: {
    backdropFilter: "blur(0px)",
  },
  tableHeader: {
    padding: "2vh 1vw",
  },
  tableCell: {
    padding: "1.5vh 1vw",
    cursor: "default",
  },
  hiddenTableCell: {
    borderBottom: "none !important",
    boxShadow: "none !important",
  },
  table: {
    boxShadow: "0px 1px 4px 0 rgba(92, 101, 132, 0.18)",
    //border: 'solid 1px rgba(0, 0, 0, 0.1)',
    borderRadius: "4px",
  },
  miniTable: {
    boxShadow: "none",
    borderRadius: "10px",
  },
  rowLink: {
    cursor: "pointer",
    // textDecoration: 'underline',
    fontWeight: "500",
    maxWidth: "12vw",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    cursor: "pointer",
    color: "#157fff",
  },
  fileLink: {
    cursor: "pointer",
    // textDecoration: 'underline',
    maxWidth: "12vw",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    cursor: "pointer",
  },
  lockedLink: {
    fontWeight: "500",
    maxWidth: "12vw",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    overflow: "hidden",
    cursor: "not-allowed",
    color: "darkGray",
  },
  disRowLink: {
    color: "gray",
  },
  docName: {
    display: "flex",
    "&:hover": {
      "& $copyButton": {
        visibility: "initial",
      },
    },
  },

  parentName: {
    display: "flex",
    "&:hover": {
      "& $copyButton1": {
        visibility: "initial",
      },
    },
  },
});

export const apiStyles = (theme) => ({
  container: {
    border: "1px solid #D1D1D1",
    borderRadius: "6px",
    padding: "2vh 0 3vh 0",
    maxWidth: "500%",
    position: "absolute",
    top: "100%",
    marginTop: "1vh",
    right: "0",
    zIndex: "100",
    backgroundColor: theme.palette.white,
    minWidth: "300%",
  },
  thresholdInput: {
    padding: "0",
    border: "0",
    outline: "0",
    width: "90%",
  },
  dateFilterCont: {
    border: "1px solid #D1D1D1",
    borderRadius: "6px",
    padding: "2vh 0 3vh 0",
    maxWidth: "500%",
    position: "absolute",
    top: "100%",
    marginTop: "1vh",
    left: "0",
    zIndex: "100",
    backgroundColor: theme.palette.white,
    minWidth: "225%",
  },
  dayList: {
    color: "#878998",
    // border: 'solid 1px rgba(135, 137, 152,0.6)',
    borderRadius: "20px",
    fontWeight: "400",
    margin: "-9px 0",
    cursor: "pointer",
    padding: "5px 0",
    width: "48%",
    marginBottom: "2vh",
    "&:hover": {
      color: "#4484FF",
    },
  },
  uploadDate: {
    padding: "8px 0",
  },
  highlightRange: {
    color: "#4484FF",
    fontWeight: "500",
  },
  header: {
    fontWeight: "400",
    //   borderBottom: '1px solid #D1D1D1',
    padding: "0 2vh 0 2vh",
  },
  formContainer: {
    padding: "0 2vh",
  },
  dateEntry: {
    color: "rgba(117, 125, 138,0.7)",
    fontWeight: "500",
    width: "48%",

    "&:last-child": {
      marginRight: "0",
    },
  },
  dateInput: {
    borderRadius: "2px",
    border: "1px solid rgba(138, 136, 134, 0.6)",
    padding: "1vh 1vh",
    display: "flex",
    justifyContent: "space-between",
    marginTop: "0.5vh",
  },
});
