const Images = {
  search: require("../Assets/Svgs/search.svg"),
  password: require("../Assets/Svgs/password.svg"),
  email: require("../Assets/Svgs/email.svg"),
  error: require("../Assets/Svgs/error.svg"),
  showPassword: require("../Assets/Svgs/showPassword.svg"),
  hidePassword: require("../Assets/Svgs/hidePassword.svg"),
  //Footer Icons
  home: require("../Assets/Svgs/home.svg"),
  plus: require("../Assets/Svgs/plus.svg"),
  report: require("../Assets/Svgs/report.svg"),
  planning: require("../Assets/Svgs/planning.svg"),
  account: require("../Assets/Svgs/account.svg"),
  pencil: require("../Assets/Svgs/pencil.svg"),
  edit: require("../Assets/Svgs/edit.svg"),
  calendar: require("../Assets/Svgs/calendar.svg"),
  chevron: require("../Assets/Svgs/chevron.svg"),
  editImage: require("../Assets/Svgs/editImage.svg"),
  attachment: require("../Assets/Svgs/attachment.svg"),
  tick: require("../Assets/Svgs/tick.svg"),
  failure: require("../Assets/Svgs/wrong.svg"),
  addImage: require("../Assets/Svgs/addImage.svg"),
  unauthorized: require("../Assets/Svgs/unauthorized.svg"),

  //Applcation Images
  GreenTick: require("../Assets/Svgs/tick.svg"),
  loginimage: require("../Assets/Images/BhaurayaartOne.jpg").default,
  ASSOY: require("../Assets/Images/assoy.png").default,
  SlideOne: require("../Assets/Images/SlideOne.jpg").default,
  SlideTwo: require("../Assets/Images/SlideTwo.jpg").default,
  SlideThree: require("../Assets/Images/SlideThree.jpg").default,
  logoprint: require("../Assets/Images/logoprint.png").default,
  uploadImageIcon: require("../Assets/Images/UploadImageIcon.png").default,
  TotalModal: require("../Assets/Images/Dashboard1.jpg").default,
  success: require("../Assets/Images/success.png").default,
  reject: require("../Assets/Images/reject.png").default,
  editpen: require("../Assets/Images/edit.png").default,
  scannerlogo: require("../Assets/Images/scannerimage.png").default,
  tasklogo: require("../Assets/Images/task.png").default,
  unauthorizedlogo: require("../Assets/Images/unauthorized.png").default,
  downloadDashboard: require("../Assets/Images/download.png").default,
  NoDataImage: require("../Assets/Images/NoDataImage.png").default,

  tasks: require("../Assets/Svgs/tasks.svg"),
  notices: require("../Assets/Svgs/notices.svg"),
  bouncing: require("../Assets/Svgs/bouncingBall.svg"),
  download: require("../Assets/Svgs/download.svg"),
  filter: require("../Assets/Svgs/filterIcon.svg"),
  logout: require("../Assets/Svgs/logout.svg"),
};

export default Images;
